blackhole/blackhole/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    #path('', RedirectView.as_view(pattern_name='home')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='web/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/web/'), name='logout'),
    #path('api-auth/', include('rest_framework.urls')),
    path('api/client/', include('client_api.urls')),
    path('api/server/', include('server_api.urls')),
    path('web/', include('web.urls')),
]

blackhole/web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='home'),
    path('app_user/create', views.AppUserCreateView.as_view(), name='app_user_create'),
    path('app_user/', views.AppUserListView.as_view(), name='app_user_list'),
    path('app_user/delete/<int:pk>/', views.AppUserDeleteView.as_view(), name='app_user_delete'),
    path('app_user/update/<int:pk>/', views.AppUserUpdateView.as_view(), name='app_user_update'),
    path('profile/create', views.ProfileCreateView.as_view(), name='profile_create'),
    path('profile/', views.ProfileListView.as_view(), name='profile_list'),
    path('profile/delete/<int:pk>/', views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile/update/<int:pk>/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('secure_shell/create', views.SecureShellCreateView.as_view(), name='secure_shell_create'),
    path('secure_shell/', views.SecureShellListView.as_view(), name='secure_shell_list'),
    path('secure_shell/delete/<int:pk>/', views.SecureShellDeleteView.as_view(), name='secure_shell_delete'),
    path('secure_shell/update/<int:pk>/', views.SecureShellUpdateView.as_view(), name='secure_shell_update'),
    path('database/create', views.DataBaseCreateView.as_view(), name='database_create'),
    path('database/', views.DatabaseListView.as_view(), name='database_list'),
    path('database/delete/<int:pk>/', views.DatabaseDeleteView.as_view(), name='database_delete'),
    path('database/update/<int:pk>/', views.DatabaseUpdateView.as_view(), name='database_update'),
    path('environment/create', views.EnvironmentCreateView.as_view(), name='environment_create'),
    path('environment/', views.EnvironmentListView.as_view(), name='environment_list'),
    path('environment/delete/<int:pk>/', views.EnvironmentDeleteView.as_view(), name='environment_delete'),
    path('environment/update/<int:pk>/', views.EnvironmentUpdateView.as_view(), name='environment_update'),
    path('privatekey/create', views.PrivateKeyCreateView.as_view(), name='privatekey_create'),
    path('privatekey/', views.PrivateKeyListView.as_view(), name='privatekey_list'),
    path('privatekey/delete/<int:pk>/', views.PrivateKeyDeleteView.as_view(), name='privatekey_delete'),
    path('privatekey/update/<int:pk>/', views.PrivateKeyUpdateView.as_view(), name='privatekey_update'),
    path('secure_shell_connection/create', views.SecureShellConnectionCreateView.as_view(), name='secure_shell_connection_create'),
    path('secure_shell_connection/', views.SecureShellConnectionListView.as_view(), name='secure_shell_connection_list'),
    path('secure_shell_connection/delete/<int:pk>/', views.SecureShellConnectionDeleteView.as_view(), name='secure_shell_connection_delete'),
    path('secure_shell_connection/update/<int:pk>/', views.SecureShellConnectionUpdateView.as_view(), name='secure_shell_connection_update'),
    path('database_connection/create', views.DataBaseConnectionCreateView.as_view(), name='database_connection_create'),
    path('database_connection/', views.DataBaseConnectionListView.as_view(), name='database_connection_list'),
    path('database_connection/delete/<int:pk>/', views.DataBaseConnectionDeleteView.as_view(), name='database_connection_delete'),
    path('database_connection/update/<int:pk>/', views.DataBaseConnectionUpdateView.as_view(), name='database_connection_update'),
    path('configuration/license/', views.LicenseManagementView.as_view(), name='manage_license'),

    #Admin
    path('admin_user/create', views.AdminUserCreateView.as_view(), name='admin_user_create'),
    path('admin_user/', views.AdminUserListView.as_view(), name='admin_user_list'),
    path('admin_user/delete/<int:pk>/', views.AdminUserDeleteView.as_view(), name='admin_user_delete'),
    path('admin_user/update/<int:pk>/', views.AdminUserUpdateView.as_view(), name='admin_user_update'),
    path('group/create', views.GroupCreateView.as_view(), name='group_create'),
    path('group/update/<int:pk>/', views.GroupUpdateView.as_view(), name='group_update'),
    path('group/delete/<int:pk>/', views.GroupDeleteView.as_view(), name='group_delete'),
    path('group/', views.GroupListView.as_view(), name='group_list'),
    path('session_record/search', views.FindSessionRecordView.as_view(), name='find_sessionlog'),
    # #Template View
    path('sessions/get_active', views.ActiveSessionTemplateView.as_view(), name='active_sessions'),
    # #web services
    path('services/get_sessions', views.get_sessions, name='get_sessions_ws'),
    path('services/kill_session', views.kill_session, name='kill_session_ws'),
    # #function view
    path('services/session_log/download/<int:pk>', views.download_session_log, name='download_session_log'),
    # path('services/session_log/streaming/<int:pk>', views.stream_session, name='streaming_session_log'),
    path('services/private_key/generate', views.generate_key, name='generate_private_key'),
    # # Autocomplete
    path('autocomplete/secure_shell/', views.SecureShellTargetAutocomplete.as_view(), name='secure_shell_autocomplete'),
    path('autocomplete/database/', views.DatabaseTargetAutocomplete.as_view(), name='database_autocomplete'),
    path('autocomplete/environment/', views.EnvironmentAutocomplete.as_view(), name='environment_autocomplete'),
    path('autocomplete/appuser/', views.AppUserAutocomplete.as_view(), name='appuser_autocomplete'),
    path('autocomplete/profile/', views.ProfileAutocomplete.as_view(), name='profile_autocomplete'),
    path('autocomplete/privatekey/', views.PrivateKeyAutocomplete.as_view(), name='privatekey_autocomplete'),
    path('autocomplete/secure_shell_connection/', views.SecureShellConnectionAutocomplete.as_view(), name='secure_shell_connection_autocomplete'),
    path('autocomplete/database_connection/', views.DataBaseConnectionAutocomplete.as_view(), name='database_connection_autocomplete'),
    path('chat/<str:room_name>/', views.room, name='room'),
]

blackhole/web/models.py
import logging
import pwd
import os

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.utils import timezone
from django.apps import apps

import paramiko
from encrypted_model_fields.fields import EncryptedCharField, EncryptedTextField


# Create your models here.


logger = logging.getLogger(__name__)


def no_white_space_validator(value):
    if " " in value:
        raise ValidationError('White spaces not allowed')


def get_time():
    return timezone.now().time().replace(second=0)


class Environment(models.Model):
    name = models.CharField(max_length=35, unique=True, verbose_name=_("Name"))

    def __str__(self):
        return self.name

    class Meta(object):
        verbose_name = _("Environment")
        verbose_name_plural = _("Environments")
        ordering = ['name']


class Target(models.Model):
    name = models.CharField(max_length=30, verbose_name=_("Name"), validators=[no_white_space_validator])
    ip = models.GenericIPAddressField(protocol='IPv4', verbose_name=_("IP Address"))
    description = models.CharField(max_length=150, blank=True, null=True, verbose_name=_("Description"))
    environment = models.ForeignKey(Environment, verbose_name=_("Environment"), on_delete=models.CASCADE)

    # def clean(self):
    #     license = apps.get_app_config('web').license
    #     if license.is_expired:
    #         raise ValidationError(_("Expired License"))
    #     else:
    #         if not (SecureShell.objects.all().count() + Database.objects.all().count()) < license.license_data['targets']:
    #             raise ValidationError(_("Max Number of targets reached"))

    def __str__(self):
        return f"{self.name}"

    class Meta(object):
        ordering = ['name']

class SecureShell(Target):
    DEVICE_TYPE_LINUX = 0
    DEVICE_TYPE_SOLARIS = 1
    DEVICE_TYPE_AIX = 2
    DEVICE_TYPE_NETWORK = 3
    DEVICE_TYPE_OSX = 4
    DEVICE_TYPE_OTHER = 5
    DEVICE_TYPE_CHOICES = ((DEVICE_TYPE_LINUX, 'Linux'),
                           (DEVICE_TYPE_SOLARIS, 'Solaris'),
                           (DEVICE_TYPE_AIX, 'AIX'),
                           (DEVICE_TYPE_NETWORK, 'Network Device'),
                           (DEVICE_TYPE_OSX, 'OSX'),
                           (DEVICE_TYPE_OTHER, 'Other'))
    port = models.PositiveIntegerField(default=22, verbose_name=_("Port"))
    device_type = models.SmallIntegerField(choices=DEVICE_TYPE_CHOICES, default=DEVICE_TYPE_LINUX, verbose_name=_("Device Type"))

    def __str__(self):
        return "{0.name} ({0.ip}) - [{0.environment}]".format(self)

    class Meta(object):
        verbose_name = _("Secure Shell Target")
        verbose_name_plural = _("Secure Shell Targets")
        ordering = ['description', 'name']


class Database(Target):
    ENGINE_MYSQL = 0
    ENGINE_ORACLE = 1
    ENGINE_POSTGRES = 2
    ENGINE_CHOICES = ((ENGINE_ORACLE, 'Oracle'),
                      (ENGINE_MYSQL, 'MySQL'),
                      (ENGINE_POSTGRES, 'Postgres'))
    db_name = models.CharField(max_length=50)
    port = models.PositiveIntegerField(default=3306, verbose_name=_("Port"))
    engine = models.SmallIntegerField(choices=ENGINE_CHOICES, default=ENGINE_MYSQL, verbose_name=_("Engine"))

    def __str__(self):
        return "{0.name} ({0.ip}) - [{0.environment}]".format(self)

    class Meta(object):
        verbose_name = _("Database Target")
        verbose_name_plural = _("Database Targets")
        ordering = ['description', 'name']


# class RemoteDesktop(Target):
#     port = models.PositiveIntegerField(default=3389, verbose_name=_("Port"))
#     secure_rdp = models.BooleanField(default=False, verbose_name=_("Secure RDP"))
#
#     def __str__(self):
#         return "{0.name} ({0.ip}) - [{0.environment}]".format(self)
#
#     class Meta(object):
#         verbose_name = _("RDP Target")
#         verbose_name_plural = _("RDP Targets")
#         ordering = ['name']


class PrivateKey(models.Model):
    RSA_KEY_TYPE = 0
    DSA_KEY_TYPE = 1
    TYPE_CHOICES = (
                    (RSA_KEY_TYPE, 'RSA'),
                    (DSA_KEY_TYPE, 'DSA'),
                    )
    user = models.CharField(max_length=30, validators=[no_white_space_validator], verbose_name=_("User"))
    environment = models.ForeignKey(Environment, verbose_name=_("Environment"), on_delete=models.CASCADE)
    key_type = models.IntegerField(choices=TYPE_CHOICES, default=RSA_KEY_TYPE, verbose_name=_("Key Type"))
    private_key = EncryptedTextField(verbose_name=_("Private Key"))
    public_key = EncryptedTextField(verbose_name=_("Public Key"))

    def __str__(self):
        return f"{_('User')}: {self.user} - {_('Environment')}: {self.environment.name} ({self.get_key_type_display()})"

    def readlines(self):
        pk_to_string = str(self.private_key).replace('\r', '')
        return pk_to_string.split('\n')

    class Meta(object):
        unique_together = ('user', 'environment')
        verbose_name = _("Private Key")
        verbose_name_plural = _("Private Keys")
        ordering = ['user', 'environment']


# class TargetConnection(models.Model):
#     target = models.ForeignKey(Target, verbose_name=_("Target"), on_delete=models.CASCADE)
#     user = models.CharField(max_length=30, validators=[no_white_space_validator], verbose_name=_("User"))
#
#     def get_connection(self):
#         target_class = type(self.target)
#         if target_class == SecureShell:
#             return self.secureshellconnection
#         elif target_class == Database:
#             return self.databaseconnection
#         elif target_class == RemoteDesktop:
#             return self.rdpconnection
#
#     class Meta(object):
#         unique_together = ('target', 'user')
#         ordering = ['target', 'user']



class SecureShellConnection(models.Model):
    AUTHENTICATION_METHOD_PRIVATE_KEY = 0
    AUTHENTICATION_METHOD_PASSWORD = 1
    AUTHENTICATION_METHODS_CHOICES = ((AUTHENTICATION_METHOD_PRIVATE_KEY, _('Private Key')),
                                      (AUTHENTICATION_METHOD_PASSWORD, _('Password')))
    authentication_method = models.SmallIntegerField(default=AUTHENTICATION_METHOD_PRIVATE_KEY,
                                                     choices=AUTHENTICATION_METHODS_CHOICES,
                                                     verbose_name=_("Authentication Method"))
    target = models.ForeignKey(SecureShell, verbose_name=_("Secure Shell"), on_delete=models.CASCADE)
    user = models.CharField(max_length=30, validators=[no_white_space_validator], verbose_name=_("User"))
    password = EncryptedCharField(max_length=100, verbose_name=_('Password'), blank=True, null=True)

    def __str__(self):
        return f"{self.target} as {self.user} using {self.get_authentication_method_display()}"

    def get_private_key(self, user):
        try:
            pk = PrivateKey.objects.get(user=user, environment=self.target.environment)
            try:

                if pk.key_type == PrivateKey.DSA_KEY_TYPE:
                    key = paramiko.DSSKey.from_private_key(pk)
                elif pk.key_type == PrivateKey.RSA_KEY_TYPE:
                    key = paramiko.RSAKey.from_private_key(pk)
            except Exception as e:
                logger.error("Invalid Private Key for user {%s} to host {%s} <{%}>", user, self.target, e.message)
                raise Exception("Invalid Private Key")
            else:
                return key
        except PrivateKey.DoesNotExist as e:
            logger.error("Missing Private Key for user {0} to host {1}".format(user, self.target))
            raise Exception("Missing Private Key")

    class Meta(object):
        unique_together = ('target', 'user')
        verbose_name = _("SecureShell Connection")
        verbose_name_plural = _("SecureShell Connections")
        ordering = ['target', 'user']


class DatabaseConnection(models.Model):
    target = models.ForeignKey(Database, verbose_name=_("Database"), on_delete=models.CASCADE)
    user = models.CharField(max_length=30, validators=[no_white_space_validator], verbose_name=_("User"))
    password = EncryptedCharField(max_length=100, verbose_name=_('Password'))

    def __str__(self):
        return f"{self.target} as {self.user}"

    def get_client_command(self):
        if self.target.engine == Database.ENGINE_MYSQL:
            return f"{settings.MYSQL_CLIENT} -u {self.user} -p{self.password} -D {self.target.db_name} -h {self.target.ip} -P {self.target.port}"
        elif self.target.engine == Database.ENGINE_ORACLE:
            return f"{settings.ORACLE_CLIENT} {self.user}/{self.password}@//{self.target.ip}:{self.target.port}/{self.target.db_name}"
        elif self.target.engine == Database.ENGINE_POSTGRES:
            return f"{settings.POSTGRES_CLIENT} 'postgresql://{self.user}:{self.password}@{self.target.ip}:{self.target.port}/{self.target.db_name}'"
        else:
            return ""

    class Meta(object):
        verbose_name = _("Database Connection")
        verbose_name_plural = _("Databases Connections")
        ordering = ['target', 'user']


# class RDPConnection(models.Model):
#     target = models.ForeignKey(SecureShell, verbose_name=_("Secure Shell"), on_delete=models.CASCADE)
#     user = models.CharField(max_length=30, validators=[no_white_space_validator], verbose_name=_("User"))
#     domain = models.CharField(max_length=50, verbose_name=_("Domain"))
#     password = EncryptedCharField(max_length=100, verbose_name=_('Password'))
#
#     def __str__(self):
#         return f"{self.target} as {self.domain}\{self.user}"
#
#     class Meta(object):
#         verbose_name = _("RDP Connection")
#         verbose_name_plural = _("RDP Connections")
#         ordering = ['target', 'user']


class Profile(models.Model):

blackhole/templates/web/_ajax_search.html
{% load static %}

<script src="{% static 'js/select2.full.min.js' %}"></script>
<script>
    function searchElement(){
        var host = $(".search-autocomplete").select2('data');
        if (host.length === 1){
            var url = $("#search-data").data("update-url") + host[0].id +'/';
            window.location = url;
        }
    }

    $(".search-autocomplete").select2({
        tags: true,
        //tokenSeparators: [","],
        multiple: false,
        placeholder: $("#search-data").data("placeholder"),
        ajax: {
            url: $("#search-data").data("autocomplete-url"),
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    q: params.term, // search term
                    page: params.page
                };
            },
            processResults: function (data, params) {
                // parse the results into the format expected by Select2
                // since we are using custom formatting functions we do not need to
                // alter the remote JSON data, except to indicate that infinite
                // scrolling can be used
                params.page = params.page || 1;

                return {
                    results: data.results,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },
            cache: true
        },
        //escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
        minimumInputLength: 1,
        //templateResult: formatUpdate, // omitted for brevity, see the source of this page
        //templateSelection: formatUpdateSelection // omitted for brevity, see the source of this page
    });

    $('.search-autocomplete').on("select2:selecting", function(e) {
        $("#search_button").attr('disabled', false);
    });
</script>

blackhole/templates/web/_list.html
{% extends "web/base.html" %}
{% load i18n static %}
{% block extra_css %}
    {#    <link href="/static/selectable/css/dj.selectable.css" type="text/css" media="all" rel="stylesheet" xmlns="http://www.w3.org/1999/html">#}
    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet">
{% endblock %}

{% block main_content %}
    {% block list_table %}
    {% endblock %}
    <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}

blackhole/templates/web/admin_user_form.html
{% extends "web/base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% block title %}{% trans 'Create' %} {% trans 'User' %}{% endblock %}

{% block extra_js %}
    <script type="application/javascript">
    jQuery.each($("select[multiple]"), function () {
     label = $(this).parent().find("label").html();
     SelectFilter.init(this.id, label, true, "/static/");
    });
    </script>
{% endblock %}


{% block main_content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fa fa-user fa-fw"></i> {% trans 'Create' %} {% trans 'User' %}</h1>
        </div>
        <div class="col-lg-5">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "ok-circle" %} {% trans 'Create' %}
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

blackhole/templates/web/app_user_form.html
{% extends "web/base.html" %}
{% load bootstrap3 static %}
{% load i18n %}
{% block title %}{% trans 'Create' %} {% trans 'User' %}{% endblock %}

{% block extra_js %}
    <script src="{% static  "js/SelectBox.js" %}"></script>
    <script src="{% static  "js/selectFilter2.js" %}"></script>
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fa fa-user fa-fw"></i> {% trans 'Create' %} {% trans 'User' %}</h1>
        </div>
        <div class="col-lg-5">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "ok-circle" %} {% trans 'Create' %}
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

blackhole/templates/web/database_list.html
{% extends "web/_list.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% block title %}{% trans 'Databases' %}{% endblock %}


{% block extra_js %}
    {{ block.super }}
    {% include "web/_ajax_search.html" %}
{% endblock %}

{% block list_table %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fa fa-database fa-fw"></i> {% trans 'Databases' %}</h1>
        </div>
        <div class="col-lg-4">
            <div id="search-data" data-autocomplete-url="{% url 'database_autocomplete' %}" data-placeholder="{% trans 'Search' %} {% trans 'Database' %}" data-update-url="/web/db/update/">
                <div class="form-group">
                    {#              Search:  {{ search_form.target }}#}
                    <select class="search-autocomplete form-control">
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <button id="search_button" class="btn btn-success" onclick="searchElement()" disabled><i class="fa fa-search"></i> {% trans 'Edit' %}</button>
        </div>

        {% if object_list %}
            <table class="table table-striped table-condensed">
                <thead>
                <tr>
                    <th>{% trans 'Name' %}</th>
                    <th>{% trans 'IP' %}</th>
                    <th>{% trans 'Engine' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.name }}</td>
                        <td>{{ object.ip }}</td>
                        <td>{{ object.get_engine_display }}</td>
                        <td>
                            <button class="btn btn-danger btn-xs" onclick="showModalDialog('{% url 'database_delete' object.id %}')"><i class="fa fa-trash-o fa-fw"></i></button>
                            <a class="btn btn-success btn-xs" href="{% url 'database_update' object.id %}" onclick="showLoader()"><i class="fa fa-edit fa-fw"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
                {% bootstrap_pagination  page_obj %}
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

blackhole/templates/web/environment_form.html
{% extends "web/base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% block title %}{% trans 'Create' %} {% trans 'Environment' %}{% endblock %}

{% block main_content %}
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><i class="fa fa-archive fa-fw"></i> {% trans 'Create' %} {% trans 'Environment' %}</h1>
                </div>
            <div class="col-lg-5">
                <form action="" method="post" class="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "ok-circle" %} {% trans 'Create' %}
                        </button>
                    {% endbuttons %}
                </form>
            </div>
            </div>
{% endblock %}

blackhole/templates/web/privatekey_confirm_delete.html
{% url 'privatekey_delete' object.id as action_url %}
{% include 'web/_confirm_delete.html' %}

blackhole/templates/web/profile_confirm_delete.html
{% url 'profile_delete' object.id as action_url %}
{% include 'web/_confirm_delete.html' %}

blackhole/templates/web/secure_shell_connection_form.html
{% extends "web/base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% block title %}{% trans 'Create' %} {% trans 'Secure Shell Connection' %}{% endblock %}

{% block extra_js %}
    <script type="application/javascript">
    function validate_authentication_method(event){
        authentication_method = $('#id_authentication_method').val();
        if (authentication_method == 1){
            if ($('#id_password').val() == ""){
                $('#id_password').parent().addClass('has-error');
                $('#password_error_message').html('Add password');
                event.preventDefault();
            }
        }else{
            if ($('#id_password').val() != ""){
               $('#id_password').parent().addClass('has-error');
               $('#password_error_message').html('Remove Password for Private Key');
               event.preventDefault();
            }
        }
    }
    $('#id_password').after('<span class="help-block" id="password_error_message"></span>');
    $('#id_password').attr('type', 'password');
    $('#create_form').submit(validate_authentication_method);
    </script>
{% endblock %}

{% block main_content %}
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><i class="fa fa-user-secret fa-fw"></i><i class="fa fa-terminal fa-fw"></i> {% trans 'Create' %} {% trans 'Secure Shell Connection' %}</h1>
                </div>
            <div class="col-lg-5">
                <form action="" method="post" class="form" id="create_form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "ok-circle" %} {% trans 'Create' %}
                        </button>
                    {% endbuttons %}
                </form>
            </div>
            </div>
{% endblock %}

blackhole/templates/web/secure_shell_list.html
{% extends "web/_list.html" %}
{% load bootstrap3 static %}
{% load i18n %}
{% block title %}{% trans 'Secure Shell' %}{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% include "web/_ajax_search.html" %}
{% endblock %}

{% block list_table %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fa fa-terminal fa-fw"></i> {% trans 'Secure Shell' %}</h1>
        </div>
        <div class="col-lg-4">
            <div id="search-data" data-autocomplete-url="{% url 'secure_shell_autocomplete' %}" data-placeholder="{% trans 'Search' %} {% trans 'Secure Shell' %}" data-update-url="/web/secure_shell/update/">
                <div class="form-group">
                    <select class="search-autocomplete form-control">
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <button id="search_button" class="btn btn-success" onclick="searchElement()" disabled><i class="fa fa-search"></i> {% trans 'Edit' %}</button>
        </div>

        {% if object_list %}
            <table class="table table-striped table-condensed">
                <thead>
                <tr>
                    <th>{% trans 'Name' %}</th>
                    <th>{% trans 'IP' %}</th>
                    <th>{% trans 'Type' %}</th>
                    <th>{% trans 'Environment' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.name }}</td>
                        <td>{{ object.ip }}</td>
                        <td>{{ object.get_device_type_display }}</td>
                        <td>{{ object.environment }}</td>
                        <td>
                            <button class="btn btn-xs btn-danger btn-xs" onclick="showModalDialog('{% url 'secure_shell_delete' object.id %}')"><i class="fa fa-trash-o fa-fw"></i></button>
                            <a class="btn btn-xs btn-success btn-xs" href="{% url 'secure_shell_update' object.id %}" onclick="showLoader()"><i class="fa fa-edit fa-fw"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
                {% bootstrap_pagination  page_obj %}
            {% endif %}
        {% endif %}
    </div>
{% endblock %}